<a href="https://colab.research.google.com/github/seacli/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
from IPython.display import Image

In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors


In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# number of brackets
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[5,6,4],
                        [7,8,6],
                        [9,10,12]
                        ]])
TENSOR


tensor([[[ 5,  6,  4],
         [ 7,  8,  6],
         [ 9, 10, 12]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[ 5,  6,  4],
        [ 7,  8,  6],
        [ 9, 10, 12]])

https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data`

https://docs.pytorch.org/docs/stable/generated/torch.rand.html#torch-rand

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1349, 0.9502, 0.3046, 0.2914],
        [0.1729, 0.4239, 0.3303, 0.0803],
        [0.8084, 0.3953, 0.1832, 0.2813]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor

tensor([[[0.2579, 0.1078, 0.2066],
         [0.0635, 0.8395, 0.5697],
         [0.8286, 0.3966, 0.5917],
         ...,
         [0.4788, 0.3129, 0.9544],
         [0.6242, 0.6591, 0.1090],
         [0.7679, 0.0218, 0.4977]],

        [[0.3582, 0.4407, 0.0968],
         [0.9602, 0.1061, 0.1042],
         [0.1755, 0.9085, 0.7609],
         ...,
         [0.7550, 0.5304, 0.1681],
         [0.0725, 0.4132, 0.0011],
         [0.4886, 0.1218, 0.1987]],

        [[0.8662, 0.1205, 0.6225],
         [0.2831, 0.4879, 0.4734],
         [0.0041, 0.3395, 0.9772],
         ...,
         [0.6491, 0.9318, 0.3903],
         [0.3651, 0.6839, 0.1697],
         [0.2479, 0.1476, 0.5187]],

        ...,

        [[0.7893, 0.7963, 0.2804],
         [0.5090, 0.3457, 0.6650],
         [0.2741, 0.1970, 0.7302],
         ...,
         [0.1687, 0.1441, 0.3480],
         [0.0475, 0.9333, 0.2180],
         [0.3964, 0.1637, 0.4490]],

        [[0.7339, 0.5965, 0.3739],
         [0.0306, 0.3898, 0.2766],
         [0.

In [20]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [24]:
# Use torch.arange()
one_to_ten = torch.arange(0, 10, .5)
one_to_ten

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g float32 or 64)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor.dtype

torch.float16

## Getting information from tensors (Attributes)

In [33]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8166, 0.8022, 0.8849, 0.6339],
        [0.6005, 0.1948, 0.7404, 0.4487],
        [0.1006, 0.7070, 0.8379, 0.5691]])

In [35]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8166, 0.8022, 0.8849, 0.6339],
        [0.6005, 0.1948, 0.7404, 0.4487],
        [0.1006, 0.7070, 0.8379, 0.5691]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device tensor is on: cpu
