<a href="https://colab.research.google.com/github/seacli/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [33]:
from IPython.display import Image

In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors


In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# number of brackets
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
# TENSOR
TENSOR = torch.tensor([[[5,6,4],
                        [7,8,6],
                        [9,10,12]
                        ]])
TENSOR


tensor([[[ 5,  6,  4],
         [ 7,  8,  6],
         [ 9, 10, 12]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([1, 3, 3])

In [32]:
TENSOR[0]

tensor([[ 5,  6,  4],
        [ 7,  8,  6],
        [ 9, 10, 12]])

https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data`

https://docs.pytorch.org/docs/stable/generated/torch.rand.html#torch-rand

In [37]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7407, 0.0477, 0.8067, 0.5959],
        [0.2430, 0.2408, 0.8659, 0.6778],
        [0.0015, 0.8116, 0.0043, 0.5209]])

In [38]:
random_tensor.ndim

2

In [39]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor

tensor([[[0.3364, 0.8668, 0.9588],
         [0.0669, 0.7305, 0.8530],
         [0.3427, 0.5617, 0.2237],
         ...,
         [0.0900, 0.9567, 0.2565],
         [0.1305, 0.2235, 0.4836],
         [0.4286, 0.4434, 0.0174]],

        [[0.1263, 0.2928, 0.5049],
         [0.5941, 0.8510, 0.6991],
         [0.6748, 0.5359, 0.2809],
         ...,
         [0.5422, 0.0414, 0.7110],
         [0.0144, 0.1742, 0.5926],
         [0.9683, 0.7293, 0.1260]],

        [[0.0509, 0.3729, 0.1663],
         [0.2568, 0.9128, 0.6517],
         [0.3481, 0.9492, 0.7311],
         ...,
         [0.4935, 0.4910, 0.9497],
         [0.6138, 0.3689, 0.6610],
         [0.8068, 0.0633, 0.9555]],

        ...,

        [[0.3202, 0.1781, 0.9212],
         [0.7222, 0.1852, 0.4305],
         [0.2704, 0.2979, 0.3736],
         ...,
         [0.1521, 0.9413, 0.2107],
         [0.7287, 0.3623, 0.3314],
         [0.1486, 0.1486, 0.5213]],

        [[0.6661, 0.5265, 0.7945],
         [0.8343, 0.9319, 0.2537],
         [0.

In [42]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)